[system]
	structure = "../data/topo.pdb"
[[group]]
	atom_list = "all"
	initial_temperature = 300.0
[[potential]]
	type = "SIESTA"
	siesta_options = """
	xc.functional          GGA
	xc.authors             revPBE

	PAO.BasisSize          TZP
	Mesh.Cutoff            300 Ry
	PAO.EnergyShift        10 meV
	PAO.SoftDefault        T

	SCF.Mixer.Variant      Pulay
	SCF.Mixer.History      8
	DM.NumberPulay         8
	DM.Tolerance           1.d-6

	SolutionMethod         diagon
	ElectronicTemperature  1 meV
	# If you do not have ELPA installed, comment out this line:
	Diag.Algorithm         ELPA-1stage
	"""
	siesta_command = "mpirun -np 90 /path/to/siesta"
	pseudopotential_dir = "../data"
[[potential]]
	type = "DFTD3"
	functional = "revpbe"
[[potential]]
	type = "PLUMED"
	file_name = "../data/plumed.2.inp"
[integrator]
	type = "OBABO"
	timestep = 0.001
	temperatures = 300.0
	relaxation_times = 0.1
[active_learning]
	n_iterations = 4
	n_potentials = 4
	msd_lower_limit = 200.0
	msd_upper_limit = 400.0
	max_md_runs_per_iter = 1
	max_md_steps_per_iter = 250000
	min_new_structures_per_iter = 20
	max_new_structures_per_iter = 100
	initial_training_set = "../training_step_1/training_iter_4/train.xyz"
	initial_potential_files = [
		"../training_step_1/training_iter_4/potential_0/nep.txt",
		"../training_step_1/training_iter_4/potential_1/nep.txt",
		"../training_step_1/training_iter_4/potential_2/nep.txt",
		"../training_step_1/training_iter_4/potential_3/nep.txt",
	]
	nep_options = """
	n_max      4 4
	cutoff     8 6
	neuron     10
	lambda_v   0.0
	batch      1000
	generation 60000
	"""
	nep_command = "/path/to/nep"
	energy_shift = -2199303.769
