[system]
	structure = "./data/H2O.pdb"
[[group]]
	atom_list = "all"
	initial_temperature = 300.0
[[potential]]
	type = "SIESTA"
	siesta_options = """
	xc.functional          GGA
	xc.authors             revPBE

	PAO.BasisSize          DZP
	Mesh.Cutoff            300 Ry
	PAO.EnergyShift        10 meV
	PAO.SoftDefault        T

	SCF.Mixer.Variant      Pulay
	SCF.Mixer.History      8
	DM.NumberPulay         8
	DM.Tolerance           1.d-5
	DM.UseSaveDM           T
	DM.History.Depth       5

	SolutionMethod         diagon
	ElectronicTemperature  1 meV
	# If you do not have ELPA installed, comment out this line:
	Diag.Algorithm         ELPA-1stage
	"""
	siesta_command = "mpirun -np 90 /path/to/siesta"
	pseudopotential_dir = "./data"
[[potential]]
	type = "DFTD3"
	functional = "revpbe"
[integrator]
	type = "BAOAB"
	timestep = 0.0005
	temperatures = 300.0
	relaxation_times = 0.1
[[trajectory]]
	format = "H5"
	interval = 1
[[logger]]
	format = "CSV"
	interval = 1
[run]
	n_steps = 25000
